
--drop table POST;

CREATE TABLE post (
    post_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    MEMBER_ID NUMBER(10),
    content CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 제약조건 드랍
ALTER TABLE POST
DROP CONSTRAINT FK_USER_NAME;

-- 제약조건 syntax
/* 
ALTER TABLE 현재테이블명
ADD CONSTRAINT 외래키이름 FOREIGN KEY (현재테이블의속성)
REFERENCES 다른테이블명 (다른테이블의유니크속성);
*/
ALTER TABLE POST
ADD CONSTRAINT FK_MEMBER_MEMBER_NAME FOREIGN KEY (MEMBER_NAME)
REFERENCES MEMBER (MEMBER_NAME);

--속성명 변경
/* 
ALTER TABLE 테이블명
RENAME COLUMN 기존속성명 TO 새로운속성명;
*/
ALTER TABLE POST
RENAME COLUMN MEMBER_ID TO MEMBER_NAME;


-- 속성 타입 변경
/*
ALTER TABLE 테이블명
MODIFY 컬럼명 새로운데이터타입;
*/
ALTER TABLE POST
MODIFY MEMBER_NAME VARCHAR2(100 BYTE);

--TRUNCATE TABLE POST;

--commit;

truncate table post;

INSERT INTO post (post_title, member_name, post_content, created_at, updated_at)
VALUES ('안녕하세요_2', 'member_2','exampleContent_2' , SYSTIMESTAMP, SYSTIMESTAMP);



--ALTER TABLE POST
--MODIFY UPDATED_AT NULL;




--
CREATE SEQUENCE post_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


--
ALTER TABLE post
    MODIFY id DEFAULT post_seq.NEXTVAL;


--
DROP SEQUENCE post_seq;

--commit;