CREATE TABLE POSTTAG (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    POST_ID NUMBER,
    TAG_ID NUMBER,
    PRIMARY KEY (ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID)
);

INSERT INTO POSTTAG(POST_ID,TAG_ID) VALUES (82,11);
--81 82 10 11