
--drop table POST;

CREATE TABLE post (
    post_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    MEMBER_ID NUMBER(10),
    content CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- foreign key
ALTER TABLE POST
ADD CONSTRAINT fk_user_name
FOREIGN KEY (member_id)
REFERENCES MEMBER(member_id);

--truncate table post;

INSERT INTO post (title, member_id, content, created_at, updated_at)
VALUES ('test1', '6','exampleContent' , SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO post (title, member_id, content, created_at, updated_at)
VALUES ('test2', '7','exampleContent' , SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO post (title, member_id, content, created_at, updated_at)
VALUES ('test3', '8','exampleContent' , SYSTIMESTAMP, SYSTIMESTAMP);



--
CREATE SEQUENCE post_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


--
ALTER TABLE post
    MODIFY id DEFAULT post_seq.NEXTVAL;


--
DROP SEQUENCE post_seq;

--commit;