ALTER TABLE POST ADD POST_CONTENT VARCHAR2(4000);
ALTER TABLE POST DROP COLUMN CONTENT;
ALTER TABLE POST RENAME COLUMN TITLE TO POST_TITLE;

--COMMIT;


--DROP TABLE POST_TAGS;

--CREATE TABLE POST_TAGS (
--  POST_ID NUMBER,
--  TAG_ID NUMBER,
--  PRIMARY KEY (POST_ID, TAG_ID),
--  FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID),
--  FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID)
--);
--
----COMMIT;
--
--INSERT INTO POST_TAGS(POST_ID,TAG_ID) VALUES (21,1);
--INSERT INTO POST_TAGS(POST_ID,TAG_ID) VALUES (24,2);
--INSERT INTO POST_TAGS(POST_ID,TAG_ID) VALUES (25,3);
--
--
--
--DROP TABLE POST_TAGS;
