truncate table member cascade;

drop table role;

CREATE TABLE role (
  key VARCHAR2(50) PRIMARY KEY,
  title VARCHAR2(50) NOT NULL
);

INSERT INTO role (key, title) VALUES ('ROLE_USER', '일반사용자');
INSERT INTO role (key, title) VALUES ('ROLE_ADMIN', '관리자');

UPDATE member
SET role = 'ROLE_USER'
WHERE role = 2;

ALTER TABLE member
MODIFY (ROLE VARCHAR2(50 BYTE));

UPDATE member
SET role = NULL
WHERE role = 2;

ALTER TABLE member
MODIFY (role VARCHAR2(50 BYTE));

UPDATE member
SET role = 'ROLE_USER'
WHERE role IS NULL;

ALTER TABLE member
DROP CONSTRAINT UNIQUE_MEMBER_NAME;

COMMIT;

truncate table role;

insert into role(key,title) values ('ADMIN','관리자');

drop table role;

CREATE TABLE ROLE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR2(50) NOT NULL
);

INSERT INTO ROLE (role) VALUES ('ROLE_USER');
INSERT INTO ROLE (role) VALUES ('ROLE_ADMIN');

commit;
