CREATE TABLE LIKES (
    id NUMBER PRIMARY KEY,
    post_id NUMBER,
    member_id NUMBER,
    FOREIGN KEY (post_id) REFERENCES POST(post_id),
    FOREIGN KEY (member_id) REFERENCES MEMBER(member_id)
);

ALTER TABLE POST ADD like_count NUMBER DEFAULT 0;


CREATE SEQUENCE likes_seq START WITH 1 INCREMENT BY 1;


ALTER TABLE likes
MODIFY id NUMBER DEFAULT likes_seq.NEXTVAL;

--commit;