

CREATE TABLE post (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

--truncate table post;

INSERT INTO post (title, content, created_at, updated_at)
VALUES ('예제 TITLE', '내용 String', SYSTIMESTAMP, SYSTIMESTAMP);


-- 시퀀스 생성
CREATE SEQUENCE post_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- 테이블에 시퀀스 연결
ALTER TABLE post
    MODIFY id DEFAULT post_seq.NEXTVAL;


-- 시퀀스 삭제
DROP SEQUENCE post_seq;

commit;