-- 태그 테이블 생성
CREATE TABLE TAGS (
    TAG_ID NUMBER PRIMARY KEY,
    TAG_NAME VARCHAR2(50) NOT NULL
);

-- 게시물과 태그 간의 관계를 맺기 위한 중간 테이블
CREATE TABLE POST_TAGS (
    POST_ID NUMBER,
    TAG_ID NUMBER,
    PRIMARY KEY (POST_ID, TAG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POST (POST_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID)
);
